name: Python CI/CD in GitHub Actions

on:
  push:
    branches:
      - dev
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar tests
        run: pytest --cov=. --cov-report=xml --cov-report=term

      - name: Verificar Archivos
        run: ls -la

      - name: Verificar reporte de cobertura
        run: grep "filename=" coverage.xml | head

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@e44258b109568baa0df60ed515909fc6c72cba92
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        with:
          args: >
            -Dsonar.projectKey=hungles_python-ci-cd
            -Dsonar.organization=hungles
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=app
            -Dsonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.venv/**,**/k8s/**
            -Dsonar.tests=test
            -Dsonar.test.inclusions=**/test_*.py,**/*_test.py
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=**/test/**
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  docker-deploy-master:
    if: github.ref == 'refs/heads/master'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t hunglespro/python-ci-cd:prod-${{ github.sha }} .

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Subir imagen
        run: docker push hunglespro/python-ci-cd:prod-${{ github.sha }}
  
  docker-deploy-staging:
    if: github.ref == 'refs/heads/staging'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t hunglespro/python-ci-cd:staging-${{ github.sha }} .

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Subir imagen
        run: docker push hunglespro/python-ci-cd:staging-${{ github.sha }}

  deploy-k8-staging:
    if: github.ref == 'refs/heads/staging'
    needs: docker-deploy-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Crear kubeconfig
        run: |
          mkdir -p $HOME/.kube
          printf "%s" "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        
      - name: Validar cluster
        run: kubectl get nodes

      - name: Aplicar manifests
        run: |
          kubectl apply -f k8s/staging/k8s-deployment.yml
          kubectl apply -f k8s/staging/k8s-service.yml
      
      - name: Actualizar imagen en manifiesto
        run: |
          kubectl set image deployment/stag-python-ci-cd-deploy stag-python-ci-cd-action=hunglespro/python-ci-cd:staging-${{ github.sha }}

      - name: Dormir para esperar despliegue
        run: sleep 60

      - name: Ver pods
        run: kubectl get pods

      - name: Ver servicios
        run: kubectl get services

  deploy-k8-master:
    if: github.ref == 'refs/heads/masters'
    needs: docker-deploy-master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Crear kubeconfig
        run: |
          mkdir -p $HOME/.kube
          printf "%s" "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Configurar kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
        
      - name: Validar cluster
        run: kubectl get nodes

      - name: Aplicar manifests
        run: |
          kubectl apply -f k8s/prod/k8s-deployment.yml
          kubectl apply -f k8s/prod/k8s-service.yml
      
      - name: Actualizar imagen en manifiesto
        run: |
          kubectl set image deployment/prod-python-ci-cd-deploy prod-python-ci-cd-action=hunglespro/python-ci-cd:prod-${{ github.sha }}

      - name: Dormir para esperar despliegue
        run: sleep 60

      - name: Ver pods
        run: kubectl get pods

      - name: Ver servicios
        run: kubectl get services
